### PR TITLE
Refs #32765 - fix for allow pulp service check

### PR DESCRIPTION
**Pull request by lzap**
Forgot to add a require.

### CODE REVIEW

**Comment by ehelms** [comment]
@lzap Will you rebase this on master now that I have merged the CI testing?

**Comment by lzap** [comment]
Sure.

**Comment by ekohl** [comment]
Looks like bzip2 is missing in the containers. I opened https://github.com/Katello/katello-selinux/pull/37 to see what else is missing.

**Review by ekohl — APPROVED** [review]
In https://github.com/Katello/katello-selinux/pull/37 I've shown that it at least compiles (if we add bzip2 and perl-podlators to CI)

**Comment by lzap** [comment]
We landed on merging https://github.com/Katello/katello-selinux/pull/37

**Pull request closed without merging**
