### PR TITLE
Refs #30087 - allow candlepin to bind port 23443

### PR DESCRIPTION
**Pull request by ehelms**
This includes https://github.com/Katello/katello-selinux/pull/26 with the added require on `tomcat_t`.

### CODE REVIEW

**Comment by ehelms** [comment]
Our project is the one choosing to deploy Candlepin onto the 23443 port. Therefore it falls to us to configure SELinux rather than asking Candlepin to manage every non-standard port. This is a follow up to https://github.com/Katello/katello-selinux/commit/85e372a3e34319331a5f9ec0fa3e46d10a3853d0

**Comment by ekohl** [comment]
Yes, but it implies that if I want to deploy candlepin on a server, I need to install `katello-selinux`, or install Candlepin on port 8443?

**Comment by ehelms** [comment]
Depends, if you want a co-located smart proxy running on it's native port
then you'd need to deploy one or the other on a nonstandard port. But these
are our problems not Candlepins. I could introduce a
katello-candlepin-selinux package and policy.

**Comment by evgeni** [comment]
IMHO having this in katello-selinux is fine, as the port is a specific of the *katello* deployment

**Pull request merged**
