### PR TITLE
Fixes #9216 - added passenger_can_connect_to_http_proxy bool

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by jlsherrill** [comment]
Is there an easy way to test this?  Configure katello to use a proxy perhaps?

**Comment by jlsherrill** [comment]
I don't actually see this in the foreman-selinux package, which is partially why i want to test it :)

**Comment by lzap** [comment]
katello-installer --katello-proxy-url=http://localhost --katello-proxy-port=3128

**Comment by lzap** [comment]
Foreman does not support http proxies, thats the reason why you see it here.

**Comment by jlsherrill** [comment]
ACK from me, mind rebasing lzap?

**Comment by lzap** [comment]
Rebased, thanks!

**Pull request merged**
